### ISSUE TITLE
Windows Powershell error

### ISSUE THREAD

**Issue by ChillHouse** [bdistin/OhGodMusicBot#27]
```
npm : events.js:160
At line:1 char:1
+ npm i -g windows-build-tools
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (events.js:160:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
      throw er; // Unhandled 'error' event
      ^
Error: spawn powershell.exe ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npm
 
ERR!
 Windows_NT 10.0.15063
npm
 
ERR!
 
argv
 "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" 
"windows-build-tools"
npm
 
ERR!
 
node
 v6.11.4
npm
 
ERR!
 
npm 
 v3.10.10
npm
 
ERR!
 
code
 ELIFECYCLE
npm
 
ERR!
 windows-build-tools@1.3.2 postinstall: `node ./lib/index.js`
npm
 
ERR!
 Exit status 1
npm
 
ERR!
 
npm
 
ERR!
 Failed at the windows-build-tools@1.3.2 postinstall script 'node ./lib/index.js'.
npm
 
ERR!
 Make sure you have the latest version of node.js and npm installed.
npm
 
ERR!
 If you do, this is most likely a problem with the windows-build-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs windows-build-tools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls windows-build-tools
npm ERR! There is likely additional logging output above.
npm
 
ERR!
 Please include the following file with any support request:
npm
 
ERR!
     C:\WINDOWS\system32\npm-debug.log
```

How do I fix this?!?!

**Comment by ghost** [comment]
it isn't discord.js related issue or problem so solve it yourself

**Comment by Wist9063** [comment]
just use cmd

**Comment by Proxxa** [comment]
@Wist9063 Windows Powershell is practically cmd. The Command terminal uses Windows Powershell.

**Comment by Proxxa** [comment]
@ChillHouse try pressing the windows button and R and the same time (LMETA + R, I think.)
Then, in the newfangled box that popped up, type "cmd" and hit enter.
Now you have a command terminal. **Great**
Next, type this into the command terminal: `npm i -g windows-build-tools`
If you followed the windows installation guide, you should've done this, but do it again just in case.
