### ISSUE TITLE
Bot Dont Open

### ISSUE THREAD

**Issue by Saraistupid** [bdistin/OhGodMusicBot#36]
module.js:684
    throw err;
    ^

SyntaxError: C:\Users\MyPC\Desktop\OhGodMusicBot-master\tokens.json: Unexpected
token / in JSON at position 150
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:681:27)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\MyPC\Desktop\OhGodMusicBot-master\server.js:
3:16)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)

**Comment by Emosewaj** [comment]
Remove the comment from the example JSON file. JSON files don't support comments.
