### ISSUE TITLE
FFMPEG error

### ISSUE THREAD

**Issue by AL3XPI** [bdistin/OhGodMusicBot#38]
I am hosting this bot and when I do npm start, it gives me this error if I use the ++play command on discord. Can someone please help?
PS C:\Users\Alex\Downloads\OhGodMusicBot-master> node server
ready!
C:\Users\Alex\Downloads\OhGodMusicBot-master\node_modules\discord.js\src\client\voice\pcm\FfmpegConverterEngine.js:80
  throw new Error(
  ^

Error: FFMPEG was not found on your system, so audio cannot be played. Please make sure FFMPEG is installed and in your PATH.
    at chooseCommand (C:\Users\Alex\Downloads\OhGodMusicBot-master\node_modules\discord.js\src\client\voice\pcm\FfmpegConverterEngine.js:80:9)
    at new FfmpegConverterEngine (C:\Users\Alex\Downloads\OhGodMusicBot-master\node_modules\discord.js\src\client\voice\pcm\FfmpegConverterEngine.js:45:20)
    at new AudioPlayer (C:\Users\Alex\Downloads\OhGodMusicBot-master\node_modules\discord.js\src\client\voice\player\AudioPlayer.js:19:23)
    at new VoiceConnection (C:\Users\Alex\Downloads\OhGodMusicBot-master\node_modules\discord.js\src\client\voice\VoiceConnection.js:58:19)
    at PendingVoiceConnection.upgrade (C:\Users\Alex\Downloads\OhGodMusicBot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:241:12)
    at PendingVoiceConnection.pass (C:\Users\Alex\Downloads\OhGodMusicBot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:220:28)
    at PendingVoiceConnection.checkReady (C:\Users\Alex\Downloads\OhGodMusicBot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:151:12)
    at PendingVoiceConnection.setTokenAndEndpoint (C:\Users\Alex\Downloads\OhGodMusicBot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:192:10)
    at ClientVoiceManager.onVoiceServer (C:\Users\Alex\Downloads\OhGodMusicBot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:36:74)
    at emitOne (events.js:116:13)

**Comment by Paultje52** [comment]
please read the readme: 
![image](https://user-images.githubusercontent.com/31313717/42497949-3c15f754-842b-11e8-9b96-31a5c79ab765.png)

**Comment by ghost** [comment]
If you are hosting on a platform where you are unable to download FFmpeg onto the system, do `npm i ffmpeg-binaries`
